Spree::Product.create!([
  {name: "Its gonna be a tough sell!", description: "The fashion shoot had signs that it was going off the rails yet he persists into the unknown. Forging ahead just like every other day.", available_on: "2016-02-24 00:00:00", deleted_at: nil, slug: "001", meta_description: "", meta_keywords: "", tax_category_id: 1, shipping_category_id: 1, promotionable: true, meta_title: ""},
  {name: "Good stuff!", description: "Beatae dicta sed sit omnis quia aut harum perferendis. Ad itaque error aut consequatur nesciunt eos et libero. Ad molestiae quod assumenda maiores quo quaerat. Ullam sint eos exercitationem ipsa corrupti. Qui qui eum doloribus omnis aut.", available_on: "2016-02-24 00:00:00", deleted_at: nil, slug: "002", meta_description: "", meta_keywords: "", tax_category_id: 1, shipping_category_id: 1, promotionable: true, meta_title: ""},
  {name: "I have a history of this.", description: "Once we get to the beach it's all business from here on out. Just another day at the beach. We have to be prepared for the worst this fashion shoot could get ugly, and lets just leave it at that.", available_on: "2016-02-24 00:00:00", deleted_at: nil, slug: "003", meta_description: "", meta_keywords: "", tax_category_id: 1, shipping_category_id: 1, promotionable: true, meta_title: ""},
  {name: "Unfortunate, based on limited reason.", description: "Beatae dicta sed sit omnis quia aut harum perferendis. Ad itaque error aut consequatur nesciunt eos et libero. Ad molestiae quod assumenda maiores quo quaerat. Ullam sint eos exercitationem ipsa corrupti. Qui qui eum doloribus omnis aut.", available_on: "2016-02-24 00:00:00", deleted_at: nil, slug: "004", meta_description: "", meta_keywords: "", tax_category_id: 1, shipping_category_id: 1, promotionable: true, meta_title: ""},
  {name: "Ok, you get the point.", description: "Clothing can't be worn like flowers, too bad:(", available_on: "2016-02-24 00:00:00", deleted_at: nil, slug: "005", meta_description: "", meta_keywords: "", tax_category_id: 1, shipping_category_id: 1, promotionable: true, meta_title: ""},
  {name: "It's what you wear.", description: "I have no idea how these things(clothes) work beyond putting them on one leg at a time.", available_on: "2016-02-24 00:00:00", deleted_at: nil, slug: "006", meta_description: "", meta_keywords: "", tax_category_id: 1, shipping_category_id: 1, promotionable: true, meta_title: ""},
  {name: "So difficult to choose, with so many choices.", description: "Let's do some AB testing and figure this out.", available_on: "2016-02-24 00:00:00", deleted_at: nil, slug: "007", meta_description: "", meta_keywords: "", tax_category_id: 1, shipping_category_id: 1, promotionable: true, meta_title: ""},
  {name: "Whoah, didn't see that coming.", description: "Pick yourself up and get back to that fashion shoot. You got to own it. Shake it don't break it!", available_on: "2016-02-24 00:00:00", deleted_at: nil, slug: "008", meta_description: "", meta_keywords: "", tax_category_id: 1, shipping_category_id: 1, promotionable: true, meta_title: ""},
  {name: "A proposal for exchange.", description: "I'll hit this hard!", available_on: "2016-02-24 00:00:00", deleted_at: nil, slug: "009", meta_description: "", meta_keywords: "", tax_category_id: 1, shipping_category_id: 1, promotionable: true, meta_title: ""},
  {name: "Let your freak flag fly.", description: "Birds of feather flock together.", available_on: "2016-02-24 00:00:00", deleted_at: nil, slug: "010", meta_description: "", meta_keywords: "", tax_category_id: 1, shipping_category_id: 1, promotionable: true, meta_title: ""},
  {name: "I got it, you want it!", description: "Let's just admit it, I have no business in a fashion shoot, but I can put a product in a view. Shoot!", available_on: "2016-02-24 00:00:00", deleted_at: nil, slug: "011", meta_description: "", meta_keywords: "", tax_category_id: 1, shipping_category_id: 1, promotionable: true, meta_title: ""},
  {name: "For real.", description: "Trade up!", available_on: "2016-02-24 00:00:00", deleted_at: nil, slug: "012", meta_description: "", meta_keywords: "", tax_category_id: 1, shipping_category_id: 1, promotionable: true, meta_title: ""},
  {name: "Retro rock t-shirts aren't going to cut it!", description: "I promise I won't stand on your desks.", available_on: "2016-02-24 00:00:00", deleted_at: nil, slug: "013", meta_description: "", meta_keywords: "", tax_category_id: 1, shipping_category_id: 1, promotionable: true, meta_title: ""},
  {name: "I hear a cello in the background.", description: "In all it's various forms fashion is ultimately about communication, and quite frankly some of us need help to deliver our message.", available_on: "2016-02-24 00:00:00", deleted_at: nil, slug: "014", meta_description: "", meta_keywords: "", tax_category_id: 1, shipping_category_id: 1, promotionable: true, meta_title: ""},
  {name: "I rest my case.", description: "In all it's various forms fashion is ultimately about communication, and quite frankly some of us need help to deliver our message.", available_on: "2016-02-24 00:00:00", deleted_at: nil, slug: "015", meta_description: "", meta_keywords: "", tax_category_id: 1, shipping_category_id: 1, promotionable: true, meta_title: ""}
])
